---

# Dirs
release_dir:        ~
release_target_dir: ~

# Git
release_git_dir: ~
release_repo:    ~
release_ref: master

# Whether to markup releases on original repository.
# If true, a commit referencing the release repository commit will be pushed to the original repository.
release_markup: false

# Tasks
release_tasks: []

# Add / Remove
release_add: []
release_remove: []

# Author
release_author: ~

# Regex
release_git_url_regex: '^(?P<protocol>https|git)(:\/\/|@)(?P<host>[^\/:]+)[\/:](?P<user>[^\/:]+)\/(?P<repository>.+)(?P<extension>.git)?$'
release_email_regex: '^(?P<name>.*) <(?P<email>.*)>$'
